#!/usr/bin/env python3
"""Compile canonical handbook chapters into online and installed reading copies."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from urllib.parse import unquote
ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / 'docs/handbook/book.json'
SKILL = ROOT / 'skills/portable-agentic-system'
LINK = re.compile(r'(!?\[[^\]]*\])\(([^)]+)\)')
def settings():
    return json.loads(BOOK.read_text(encoding='utf-8'))
def chapters(language):
    return [ROOT / 'docs/handbook' / language / name for name in settings()['chapters']]
def image_sources():
    images=set()
    for language in settings()['languages']:
        for source in chapters(language):
            for target in re.findall(r'!\[[^\]]*\]\(([^)]+)\)',source.read_text(encoding='utf-8')):
                path=(source.parent/unquote(target)).resolve()
                if not path.is_relative_to(ROOT) or not path.is_file():
                    raise ValueError(f'Handbook images must be local repository files: {target}')
                images.add(path)
    return sorted(images)
def output_paths(language):
    suffix = '' if language == 'en' else '.zh-CN'
    return [ROOT / f'docs/agentic-systems-field-guide{suffix}.md', SKILL / f'pas/references/master-build-playbook{suffix}.md']
def rebase_links(text, source, output):
    def replace(match):
        target = match[2]
        if target.startswith(('https://', 'http://', 'mailto:', '#')):
            return match[0]
        path, sep, anchor = target.partition('#')
        resolved = (source.parent / unquote(path)).resolve()
        relative = resolved.relative_to(ROOT)
        if output.is_relative_to(SKILL) and not resolved.is_relative_to(SKILL):
            destination = settings()['repository'] + '/blob/main/' + relative.as_posix()
            if match[1].startswith('!'):
                destination = destination.replace('https://github.com/', 'https://raw.githubusercontent.com/', 1).replace('/blob/main/', '/main/', 1)
        else:
            destination = Path(os.path.relpath(resolved, output.parent)).as_posix()
        return f'{match[1]}({destination}{sep}{anchor})'
    return LINK.sub(replace, text)
def compile_book(language, output):
    config = settings()
    meta = config['languages'][language]
    blocks = ['<!-- GENERATED by scripts/build_master_playbook.py. Edit docs/handbook chapters. -->',
              f"# {meta['title']}", f"{meta['subtitle']}\n\n@kwis7 | {config['edition']} | {config['date']}"]
    for source in chapters(language):
        blocks.append(rebase_links(source.read_text(encoding='utf-8').strip(), source, output))
    return '\n\n'.join(blocks) + '\n'
def source_manifest():
    files = [BOOK] + [p for lang in settings()['languages'] for p in chapters(lang)] + image_sources()
    return {'edition': settings()['edition'], 'date': settings()['date'],
            'sources': {p.relative_to(ROOT).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}
def generated_files():
    result = {}
    for language in settings()['languages']:
        for output in output_paths(language):
            result[output] = compile_book(language, output)
    result[ROOT / 'docs/downloads/source-manifest.json'] = json.dumps(source_manifest(), indent=2, ensure_ascii=False) + '\n'
    return result
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail when compiled reading copies are stale')
    args = parser.parse_args()
    stale = []
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    if stale:
        raise SystemExit('Generated content is stale: ' + ', '.join(stale))
    print('Reading copies are current.' if args.check else 'Built both online guides and both packaged reading copies.')
if __name__ == '__main__':
    main()
